nelmio_api_doc:
    documentation:
        info:
            title: Oldies But Goldies Berlin
            description: Oldies But Goldies Berlin Documentation
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/docu)
