nelmio_api_doc:
    documentation:
        info:
            title: Analystic Tool
            description: Analystic Tool v1
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)

