controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        tr: '' # don't prefix URLs for Turkish, the default locale
        en: '/en'
        de: '/de'
        fr: '/fr'
        el: '/el'
        ar: '/ar'
        ru: '/ru'
    requirements:
        _locale: '%app.locales%'
    defaults: { _locale: '%locale%'}

kernel:
    resource: ../../src/Kernel.php
    type: annotation
